name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      env:
        GO111MODULE: auto
        TOKEN: be8d02aa38e7c1a847ca29f8740113e5c3e9b459
        GOROOT: /usr/local/go
        GOPATH: $HOME/go 

      run: |
              git config --global url."https://rasongame:$TOKEN@github.com/".insteadOf "https://github.com/"
              go get -u github.com/slovaq/web2tg/web/API
              go get -u gorm.io/gorm
              go get -u gorm.io/driver/sqlite
              go get -u github.com/go-chi/chi
              go build -v ./...
